services:
  - type: web
    name: brackets-api
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: PORT
        value: 3001
